const PLACES = [
  {
    "id": "akademiya-supergeroev",
    "slug": "akademiya-supergeroev",
    "name": "Академия Супергероев",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Комплексный центр",
    "description": "Центр детского развития: английский, подготовка к школе, логопед, рисование, театр, танцы, айкидо, капоэйра.",
    "address": "Токсово (точный адрес требует подтверждения)",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/superherovtoksovo",
    "price": "3000–7000 ₽/мес",
    "age": "3–14",
    "format": "группы",
    "rating": "",
    "source": "чат + ранее собранные открытые данные",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "kdts-toksovo",
    "slug": "kdts-toksovo",
    "name": "КДЦ Токсово",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Муниципальный центр",
    "description": "Муниципальные кружки: рисование, вокал, танцы, мероприятия.",
    "address": "Ленинградская область, Токсово, ул. Ленина, 33",
    "district": "Токсово",
    "phone": "+7 (81370) 5-56-63",
    "website": "https://vk.com/kdctoksovo",
    "price": "бесплатно / 1000–3000 ₽",
    "age": "4–16",
    "format": "группы",
    "rating": "",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": null,
    "lng": null
  },
  {
    "id": "baletnaya-gruppa",
    "slug": "baletnaya-gruppa",
    "name": "Балетная группа",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Балет",
    "description": "Занятия балетом с профессиональным педагогом, небольшие группы.",
    "address": "КП Александрийский парк, д. Скотное",
    "district": "Скотное",
    "phone": "",
    "website": "",
    "price": "3000–5000 ₽",
    "age": "4–7",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "semeynaya-myagkaya-shkola",
    "slug": "semeynaya-myagkaya-shkola",
    "name": "Семейная мягкая школа",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Телесные практики",
    "description": "Занятия для детей и родителей, развитие через движение и взаимодействие.",
    "address": "Порошкино (точный адрес требует подтверждения)",
    "district": "≈10 км",
    "phone": "",
    "website": "https://vk.com/wall-58536241_3478",
    "price": "3000–6000 ₽",
    "age": "3–10",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "basketbol-shkolnaya-sektsiya",
    "slug": "basketbol-shkolnaya-sektsiya",
    "name": "Баскетбол (школьная секция)",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Баскетбол",
    "description": "Детская секция баскетбола при школе.",
    "address": "Токсово (школа, точный адрес требует подтверждения)",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно / символическая",
    "age": "7–16",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "severnyy-sklon-detskaya-shkola",
    "slug": "severnyy-sklon-detskaya-shkola",
    "name": "Северный склон — детская школа",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Горные лыжи / сноуборд",
    "description": "Обучение горным лыжам и сноуборду, индивидуальные и групповые занятия.",
    "address": "Ленинградская область, Токсово, ул. Офицерская, 17Б",
    "district": "Токсово",
    "phone": "+7 (911) 924-81-81",
    "website": "https://severny-sklon.ru",
    "price": "2000–6000 ₽/занятие",
    "age": "4–16",
    "format": "индивидуально / группы",
    "rating": "4.3",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1560282,
    "lng": 30.5486059
  },
  {
    "id": "kanaev-ski-club",
    "slug": "kanaev-ski-club",
    "name": "Kanaev Ski Club",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Горные лыжи",
    "description": "Горнолыжная школа с тренировками и выездами.",
    "address": "ул. Офицерская, 17Б, Токсово",
    "district": "Токсово",
    "phone": "+7 (981) 122-10-00",
    "website": "https://kanaevskiclub.ru",
    "price": "5000–15000 ₽",
    "age": "5–16",
    "format": "группы",
    "rating": "5.0",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1553068,
    "lng": 30.5496235
  },
  {
    "id": "aykido",
    "slug": "aykido",
    "name": "Айкидо",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Единоборства",
    "description": "Тренировки по айкидо для детей.",
    "address": "Токсово (площадка требует подтверждения)",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "3000–5000 ₽",
    "age": "5–14",
    "format": "группы",
    "rating": "",
    "source": "чат + каталог кружков",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "kapoeyra",
    "slug": "kapoeyra",
    "name": "Капоэйра",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Единоборства / танец",
    "description": "Бразильское боевое искусство с элементами танца.",
    "address": "Токсово (площадка требует подтверждения)",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "3000–5000 ₽",
    "age": "5–14",
    "format": "группы",
    "rating": "",
    "source": "чат + каталог кружков",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "khudozhestvennaya-studiya-kdts",
    "slug": "khudozhestvennaya-studiya-kdts",
    "name": "Художественная студия (КДЦ)",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Рисование",
    "description": "Рисование, лепка, творческие занятия.",
    "address": "ул. Ленина, 33, Токсово",
    "district": "Токсово",
    "phone": "+7 (81370) 5-56-63",
    "website": "https://vk.com/kdctoksovo",
    "price": "2000–4000 ₽",
    "age": "4–14",
    "format": "группы",
    "rating": "",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": null,
    "lng": null
  },
  {
    "id": "angliyskiy-yazyk",
    "slug": "angliyskiy-yazyk",
    "name": "Английский язык",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Языки",
    "description": "Групповые занятия английским для детей.",
    "address": "Токсово (центр требует подтверждения)",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "3000–7000 ₽",
    "age": "4–14",
    "format": "группы",
    "rating": "",
    "source": "чат + каталог кружков",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "logopedicheskie-zanyatiya",
    "slug": "logopedicheskie-zanyatiya",
    "name": "Логопедические занятия",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Логопед",
    "description": "Индивидуальные занятия по речи и подготовка к школе.",
    "address": "Токсово / Вартемяги / Кузьмолово",
    "district": "≈10 км",
    "phone": "",
    "website": "",
    "price": "1000–3000 ₽/занятие",
    "age": "3–10",
    "format": "индивидуально",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "severnyy-sklon",
    "slug": "severnyy-sklon",
    "name": "Северный склон",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Горные лыжи / сноуборд",
    "description": "Курорт с обучением, прокатом и трассами.",
    "address": "ул. Офицерская, 17Б, Токсово",
    "district": "Токсово",
    "phone": "+7 (911) 924-81-81",
    "website": "https://severny-sklon.ru",
    "price": "2000–6000 ₽/занятие",
    "age": "16+",
    "format": "индивидуально / группы",
    "rating": "4.3",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1560282,
    "lng": 30.5486059
  },
  {
    "id": "kanaev-ski-club-2",
    "slug": "kanaev-ski-club-2",
    "name": "Kanaev Ski Club",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Горные лыжи",
    "description": "Школа горных лыж, тренировки и обучение.",
    "address": "ул. Офицерская, 17Б, Токсово",
    "district": "Токсово",
    "phone": "+7 (981) 122-10-00",
    "website": "https://kanaevskiclub.ru",
    "price": "5000–15000 ₽",
    "age": "18+",
    "format": "группы",
    "rating": "5.0",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1553068,
    "lng": 30.5496235
  },
  {
    "id": "yukki-sport-club",
    "slug": "yukki-sport-club",
    "name": "Yukki Sport Club",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Горные лыжи",
    "description": "Горнолыжные занятия и тренировки.",
    "address": "ул. Офицерская, 16, Токсово",
    "district": "Токсово",
    "phone": "+7 (911) 271-86-96",
    "website": "",
    "price": "по запросу",
    "age": "16+",
    "format": "группы / индивидуально",
    "rating": "",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1564234,
    "lng": 30.5507353
  },
  {
    "id": "baza-ska-toksovo",
    "slug": "baza-ska-toksovo",
    "name": "База СКА Токсово",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Лыжная база",
    "description": "Спортивная база, лыжная подготовка.",
    "address": "Санаторная ул., 36, Токсово",
    "district": "Токсово",
    "phone": "+7 (921) 424-26-59",
    "website": "",
    "price": "по запросу",
    "age": "16+",
    "format": "база / тренировки",
    "rating": "4.3",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1535372,
    "lng": 30.5576167
  },
  {
    "id": "gornolyzhnaya-shkola-ska",
    "slug": "gornolyzhnaya-shkola-ska",
    "name": "Горнолыжная школа СКА",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Горные лыжи",
    "description": "Тренировки по лыжам.",
    "address": "Санаторная ул., 36, Токсово",
    "district": "Токсово",
    "phone": "+7 (921) 939-71-14",
    "website": "http://sca-ski.ru",
    "price": "по запросу",
    "age": "16+",
    "format": "тренировки",
    "rating": "3.6",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1602488,
    "lng": 30.5114844
  },
  {
    "id": "nikels-club",
    "slug": "nikels-club",
    "name": "Nikels Club",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Лыжный клуб",
    "description": "Лыжный клуб.",
    "address": "ул. Лесгафта, 35к1, Токсово",
    "district": "Токсово",
    "phone": "+7 (911) 844-48-15",
    "website": "https://nikels.club",
    "price": "по запросу",
    "age": "16+",
    "format": "клуб / тренировки",
    "rating": "5.0",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1781724,
    "lng": 30.5366633
  },
  {
    "id": "skillon",
    "slug": "skillon",
    "name": "Skillon",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Лыжный клуб",
    "description": "Skillon — спортивный клуб в УТЦ Кавголово, где обучают беговым лыжам и биатлону взрослых и детей от 4 лет. Занятия проходят в группах до 8 человек и индивидуально, с поэтапным освоением техники, вниманием к безопасности и комфортному темпу обучения. В клубе есть прокат инвентаря, тренировки круглый год и выездные локации для бега, лыжероллеров и ОФП.",
    "address": "УТЦ Кавголово, ул. Лесгафта, 35, Токсово",
    "district": "Токсово",
    "phone": "+7 (909) 585-77-01",
    "website": "https://skillon.ru",
    "price": "от 890 ₽",
    "age": "4+",
    "format": "клуб / тренировки / прокат",
    "rating": "5.0",
    "source": "официальный сайт Skillon, УТЦ Кавголово и 2ГИС",
    "photos": [
      "https://static.tildacdn.com/tild3130-3139-4836-b265-383132396666/IMG_8346.webp",
      "https://static.tildacdn.com/tild3063-6438-4163-b061-383130343464/IMG_8349.webp",
      "https://static.tildacdn.com/tild3034-3339-4935-a431-643763653633/IMG_8355.webp",
      "https://static.tildacdn.com/tild3130-6465-4636-a534-313335663261/IMG_8361.webp",
      "https://static.tildacdn.com/tild3061-3263-4139-b130-633132666637/IMG_8378_1.webp"
    ],
    "status": "verified_public",
    "lat": 60.177631,
    "lng": 30.5359962
  },
  {
    "id": "utts-kavgolovo",
    "slug": "utts-kavgolovo",
    "name": "УТЦ Кавголово",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Спорткомплекс",
    "description": "УТЦ Кавголово — крупный круглогодичный спортивный комплекс в Токсово. На территории есть всесезонный лыжный тоннель, лыжероллерная и лыжная трассы, биатлонное стрельбище, тренажёрный зал, площадки для игровых видов спорта, СПА и гостиничный комплекс. Рядом находятся Курголовское озеро и сосновые леса, поэтому центр подходит и для тренировок, и для отдыха.",
    "address": "ул. Лесгафта, 31, Токсово",
    "district": "Токсово",
    "phone": "+7 (812) 383-70-60",
    "website": "http://www.utc-kavgolovo.ru",
    "price": "по запросу",
    "age": "16+",
    "format": "центр / тренировки",
    "rating": "4.8",
    "source": "официальный сайт УТЦ Кавголово",
    "photos": [
      "https://www.kavgolovo.center/style/images/logo-2.png",
      "https://www.kavgolovo.center/style/images/tonnel.webp",
      "https://www.kavgolovo.center/style/products/20/small/skym.jpg",
      "https://www.kavgolovo.center/style/products/19/small/rollerm.jpg",
      "https://www.kavgolovo.center/style/products/44/small/shooting2m.jpg"
    ],
    "status": "verified_public",
    "lat": 60.176514,
    "lng": 30.5348935
  },
  {
    "id": "tay-bo",
    "slug": "tay-bo",
    "name": "Тай Бо",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Фитнес / единоборства",
    "description": "Групповые тренировки в зале на Северном склоне.",
    "address": "Северный склон, Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "~600 ₽/занятие",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "yoga",
    "slug": "yoga",
    "name": "Йога",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Йога",
    "description": "Групповые и индивидуальные занятия йогой.",
    "address": "Токсово / Кузьмолово",
    "district": "≈10 км",
    "phone": "",
    "website": "",
    "price": "500–1500 ₽",
    "age": "18+",
    "format": "группы / индивидуально",
    "rating": "",
    "source": "локальные группы / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "pilates",
    "slug": "pilates",
    "name": "Пилатес",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Фитнес",
    "description": "Укрепление мышц, работа с осанкой.",
    "address": "Токсово / рядом",
    "district": "≈10 км",
    "phone": "",
    "website": "",
    "price": "800–2000 ₽",
    "age": "18+",
    "format": "группы",
    "rating": "",
    "source": "локальные группы / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "funktsionalnye-trenirovki",
    "slug": "funktsionalnye-trenirovki",
    "name": "Функциональные тренировки",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Фитнес",
    "description": "Групповые тренировки для силы и выносливости.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "500–1500 ₽",
    "age": "18+",
    "format": "группы",
    "rating": "",
    "source": "локальные тренировки / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "beg-treylranning",
    "slug": "beg-treylranning",
    "name": "Бег / трейлраннинг",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Бег",
    "description": "Лесные маршруты, озера, самостоятельные тренировки.",
    "address": "Токсово / Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "16+",
    "format": "самостоятельно / клубы",
    "rating": "",
    "source": "инфраструктура местности",
    "status": "verified_public",
    "lat": null,
    "lng": null
  },
  {
    "id": "basketbol-lyubitelskiy",
    "slug": "basketbol-lyubitelskiy",
    "name": "Баскетбол (любительский)",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Командный спорт",
    "description": "Игры в школьных залах.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "nastolnyy-tennis",
    "slug": "nastolnyy-tennis",
    "name": "Настольный теннис",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Игровые виды",
    "description": "Возможность играть и тренироваться.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "300–1000 ₽",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "aykido-2",
    "slug": "aykido-2",
    "name": "Айкидо",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Единоборства",
    "description": "Занятия айкидо.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "3000–5000 ₽",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "каталог секций / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "boks",
    "slug": "boks",
    "name": "Бокс",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Единоборства",
    "description": "Индивидуальные и групповые тренировки.",
    "address": "Токсово / Девяткино",
    "district": "≈10 км",
    "phone": "",
    "website": "",
    "price": "1000–3000 ₽",
    "age": "18+",
    "format": "индивидуально / группы",
    "rating": "",
    "source": "локальные предложения / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "vindserfing",
    "slug": "vindserfing",
    "name": "Виндсерфинг",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Водный спорт",
    "description": "Обучение и катание на воде.",
    "address": "озера Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "2000–5000 ₽",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "локальная инфраструктура / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "sup",
    "slug": "sup",
    "name": "SUP",
    "category": "Спорт",
    "categoryId": "sport",
    "subcategory": "Водный спорт",
    "description": "Прокат и тренировки на сапах.",
    "address": "озера Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "1000–3000 ₽",
    "age": "16+",
    "format": "прокат / тренировки",
    "rating": "",
    "source": "локальная инфраструктура / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "kavgolovskoe-ozero",
    "slug": "kavgolovskoe-ozero",
    "name": "Кавголовское озеро",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Озеро / отдых",
    "description": "Главное озеро района — пляжи, прогулки, SUP, виндсерфинг.",
    "address": "Токсово, Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.8",
    "source": "карты / инфраструктура",
    "status": "verified_public",
    "lat": 60.1735,
    "lng": 30.528
  },
  {
    "id": "ozero-khepoyarvi",
    "slug": "ozero-khepoyarvi",
    "name": "Озеро Хепоярви",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Озеро / туризм",
    "description": "Крупное лесное озеро, популярное для прогулок, походов и рыбалки.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.9",
    "source": "карты",
    "status": "verified_public",
    "lat": 60.186,
    "lng": 30.492
  },
  {
    "id": "zubrovnik",
    "slug": "zubrovnik",
    "name": "Зубровник",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Экопарк",
    "description": "Питомник зубров — можно увидеть животных вблизи.",
    "address": "Токсово, ул. Совхозная",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно / донаты",
    "age": "0+",
    "format": "посещение",
    "rating": "4.7",
    "source": "карты / официальные данные",
    "status": "verified_public",
    "lat": 60.1795,
    "lng": 30.543
  },
  {
    "id": "kavgolovskie-toksovskie-vysoty",
    "slug": "kavgolovskie-toksovskie-vysoty",
    "name": "Кавголовские / Токсовские высоты",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Холмы / панорамы",
    "description": "Живописные холмы, виды, лыжи зимой, прогулки летом.",
    "address": "Кавголово / Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/toksovskie-vyisotyi.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.8",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.1762,
    "lng": 30.5361
  },
  {
    "id": "stantsiya-kavgolovo-vidovaya",
    "slug": "stantsiya-kavgolovo-vidovaya",
    "name": "Станция Кавголово (видовая)",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Видовая точка",
    "description": "Красивые виды на озеро и лес с платформы.",
    "address": "Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.6",
    "source": "карты",
    "status": "verified_public",
    "lat": 60.173,
    "lng": 30.53
  },
  {
    "id": "ekotropy-toksovo",
    "slug": "ekotropy-toksovo",
    "name": "Экотропы Токсово",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Маршруты",
    "description": "Маршруты для прогулок, бега, велосипедов.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/ecotoksovskie-vyisotyi.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.8",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.17,
    "lng": 30.52
  },
  {
    "id": "tserkov-arkhangela-mikhaila",
    "slug": "tserkov-arkhangela-mikhaila",
    "name": "Церковь Архангела Михаила",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Храм",
    "description": "Православный храм, историческое место.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "посещение",
    "rating": "4.7",
    "source": "карты",
    "status": "verified_public",
    "lat": 60.1585,
    "lng": 30.541
  },
  {
    "id": "utts-kavgolovo-2",
    "slug": "utts-kavgolovo-2",
    "name": "УТЦ Кавголово",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Спорткомплекс",
    "description": "Крупный центр лыжных и спортивных тренировок.",
    "address": "ул. Лесгафта, 31, Токсово",
    "district": "Токсово",
    "phone": "+7 (812) 383-70-60",
    "website": "http://www.utc-kavgolovo.ru",
    "price": "зависит от услуг",
    "age": "0+",
    "format": "посещение / тренировки",
    "rating": "4.8",
    "source": "официальные данные",
    "status": "verified_public",
    "lat": 60.176514,
    "lng": 30.5348935
  },
  {
    "id": "severnyy-sklon-2",
    "slug": "severnyy-sklon-2",
    "name": "Северный склон",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Курорт",
    "description": "Круглогодичная зона отдыха и спорта.",
    "address": "ул. Офицерская, 17Б, Токсово",
    "district": "Токсово",
    "phone": "+7 (911) 924-81-81",
    "website": "https://severny-sklon.ru",
    "price": "платно",
    "age": "0+",
    "format": "посещение",
    "rating": "4.3",
    "source": "официальные данные",
    "status": "verified_public",
    "lat": 60.1560282,
    "lng": 30.5486059
  },
  {
    "id": "elovye-kholmy-start",
    "slug": "elovye-kholmy-start",
    "name": "Еловые холмы — старт",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Экотропа",
    "description": "Официальная стартовая точка экотропы.",
    "address": "район платформы Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/ecotoksovskie-vyisotyi.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.188448,
    "lng": 30.547983
  },
  {
    "id": "malinovaya-gora-start",
    "slug": "malinovaya-gora-start",
    "name": "Малиновая гора — старт",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Экотропа",
    "description": "Официальная стартовая точка экотропы.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/ekomarshrut-malinovaya-gora.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.161705,
    "lng": 30.492562
  },
  {
    "id": "kurgolovskaya-etnotropa-start",
    "slug": "kurgolovskaya-etnotropa-start",
    "name": "Курголовская этнотропа — старт",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Этнотропа",
    "description": "Официальная стартовая точка этнотропы.",
    "address": "район платформы Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/kurgolovskaya-tropa.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.188448,
    "lng": 30.547983
  },
  {
    "id": "peschanaya-kosa-kavgolovo",
    "slug": "peschanaya-kosa-kavgolovo",
    "name": "Песчаная коса Кавголово",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Песчаный берег для закатов. Нужна полевая проверка перед публичным запуском.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1755,
    "lng": 30.52
  },
  {
    "id": "tikhiy-zaliv-kavgolovo",
    "slug": "tikhiy-zaliv-kavgolovo",
    "name": "Тихий залив Кавголово",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Уединённый берег. Нужна полевая проверка.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.171,
    "lng": 30.515
  },
  {
    "id": "zakatnaya-polyana",
    "slug": "zakatnaya-polyana",
    "name": "Закатная поляна",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Открытое поле для закатов. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.16,
    "lng": 30.5
  },
  {
    "id": "lesnye-skaly",
    "slug": "lesnye-skaly",
    "name": "Лесные скалы",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Каменные массивы в лесу. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.168,
    "lng": 30.51
  },
  {
    "id": "sosnovye-tropy-khepoyarvi",
    "slug": "sosnovye-tropy-khepoyarvi",
    "name": "Сосновые тропы Хепоярви",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Маршрут",
    "description": "Тихие лесные тропы. Нужна полевая проверка.",
    "address": "район Хепоярви",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.19,
    "lng": 30.48
  },
  {
    "id": "dikiy-bereg-khepoyarvi",
    "slug": "dikiy-bereg-khepoyarvi",
    "name": "Дикий берег Хепоярви",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Тихий берег без инфраструктуры. Нужна полевая проверка.",
    "address": "район Хепоярви",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.188,
    "lng": 30.495
  },
  {
    "id": "lesnaya-polyana-dlya-piknika",
    "slug": "lesnaya-polyana-dlya-piknika",
    "name": "Лесная поляна для пикника",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Отдых",
    "description": "Поляна для пикника. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1705,
    "lng": 30.5
  },
  {
    "id": "beryozovaya-roshcha",
    "slug": "beryozovaya-roshcha",
    "name": "Берёзовая роща",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Красивое место весной и осенью. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.158,
    "lng": 30.52
  },
  {
    "id": "peschanye-kholmy-u-tropy",
    "slug": "peschanye-kholmy-u-tropy",
    "name": "Песчаные холмы у тропы",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Ландшафт",
    "description": "Необычный рельеф. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.162,
    "lng": 30.505
  },
  {
    "id": "tochka-dlya-zvyozdnogo-neba",
    "slug": "tochka-dlya-zvyozdnogo-neba",
    "name": "Точка для звёздного неба",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Астроспот",
    "description": "Точка для наблюдения звёзд. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1905,
    "lng": 30.47
  },
  {
    "id": "uzkiy-lesnoy-spusk-k-vode",
    "slug": "uzkiy-lesnoy-spusk-k-vode",
    "name": "Узкий лесной спуск к воде",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Вода",
    "description": "Небольшой спуск к воде. Нужна полевая проверка.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.174,
    "lng": 30.522
  },
  {
    "id": "vysokiy-kholm-u-kavgolovo",
    "slug": "vysokiy-kholm-u-kavgolovo",
    "name": "Высокий холм у Кавголово",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Видовая",
    "description": "Видовой холм. Нужна полевая проверка.",
    "address": "Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.169,
    "lng": 30.54
  },
  {
    "id": "staryy-sosnovyy-massiv",
    "slug": "staryy-sosnovyy-massiv",
    "name": "Старый сосновый массив",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Лес",
    "description": "Массив старых сосен. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.182,
    "lng": 30.49
  },
  {
    "id": "velotropa-bez-trafika",
    "slug": "velotropa-bez-trafika",
    "name": "Велотропа без трафика",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Веломаршрут",
    "description": "Тихая лесная велотропа. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.165,
    "lng": 30.495
  },
  {
    "id": "pole-u-kromki-lesa",
    "slug": "pole-u-kromki-lesa",
    "name": "Поле у кромки леса",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Открытое пространство для фото. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.155,
    "lng": 30.51
  },
  {
    "id": "lesnaya-tropa-sledov-zhivotnykh",
    "slug": "lesnaya-tropa-sledov-zhivotnykh",
    "name": "Лесная тропа следов животных",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Природа",
    "description": "Тропа со следами животных. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.192,
    "lng": 30.475
  },
  {
    "id": "bezymyannyy-bereg-dlya-sup",
    "slug": "bezymyannyy-bereg-dlya-sup",
    "name": "Безымянный берег для SUP",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Вода",
    "description": "Спокойный берег. Нужна полевая проверка.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1765,
    "lng": 30.518
  },
  {
    "id": "malaya-smotrovaya-na-nasyp",
    "slug": "malaya-smotrovaya-na-nasyp",
    "name": "Малая смотровая на насыпь",
    "category": "Скрытые места",
    "categoryId": "hidden",
    "subcategory": "Видовая",
    "description": "Малая видовая точка. Нужна полевая проверка.",
    "address": "Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1675,
    "lng": 30.535
  }
];
