const PLACES = [
  {
    "id": "akademiya-supergeroev",
    "slug": "akademiya-supergeroev",
    "name": "Академия Супергероев",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Комплексный центр",
    "description": "Центр детского развития: английский, подготовка к школе, логопед, рисование, театр, танцы, айкидо, капоэйра.",
    "address": "Короткий пер. д. 1а ЖК «Токсово-Короткий»",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/superhero_camp",
    "price": "3000–7000 ₽/мес",
    "age": "3–14",
    "format": "группы",
    "rating": "4.6",
    "source": "чат + ранее собранные открытые данные",
    "status": "chat_only",
    "lat": 60.148095,
    "lng": 30.518878
  },
  {
    "id": "kdts-toksovo",
    "slug": "kdts-toksovo",
    "name": "КДЦ Токсово",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Муниципальный центр",
    "description": "Муниципальные кружки: рисование, вокал, танцы, мероприятия.",
    "address": "Привокзальная улица, 16А д. Рапполово, Овражная улица, 21А",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/kdctoksovo",
    "price": "бесплатно / 1000–3000 ₽",
    "age": "4–16",
    "format": "группы",
    "rating": "4.1",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.151553,
    "lng": 30.514387
  },
  {
    "id": "baletnaya-gruppa",
    "slug": "baletnaya-gruppa",
    "name": "Балетная группа",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Балет",
    "description": "Занятия балетом с профессиональным педагогом, небольшие группы.",
    "address": "КП Александрийский парк",
    "district": "Скотное",
    "phone": "",
    "website": "https://vk.com/alexandrian.park.village",
    "price": "3000–5000 ₽",
    "age": "4–7",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": 60.170352,
    "lng": 30.370558,
    "notes": "Юр. лицо было ликвидировано 04 августа 2023 г. Подробнее: https://inndex.ru/ul/skotnoe/ogrn-1204700013396-a25-ooo-baletnaya-shkola-aysedora\nhttps://vk.com/spb.park Александрийский парк"
  },
  {
    "id": "semeinaya-myagkaya-shkola",
    "slug": "semeinaya-myagkaya-shkola",
    "name": "Семейная мягкая школа",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Телесные практики",
    "description": "Занятия для детей и родителей, развитие через движение и взаимодействие. Семейная Мягкая Школа — это авторская методика телесной развивающей игротерапии для больших и маленьких. Разработана Эллой Глушковой в 1993 году.",
    "address": "ул. Моховая, д.20, Пушкин, Глинки, д.17 Всеволжск, ул. Садовая, д.8 пр. Ветеранов, д.114, к.1",
    "district": "≈10 км",
    "phone": "",
    "website": "https://vk.com/softschool",
    "price": "3000–6000 ₽",
    "age": "3–10",
    "format": "группы",
    "rating": "5.0",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": 60.029593,
    "lng": 30.643457
  },
  {
    "id": "basketbol-shkolnaya-sektsiya",
    "slug": "basketbol-shkolnaya-sektsiya",
    "name": "Баскетбол (школьная секция)",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Баскетбол",
    "description": "МОУ «Токсовский центр образования» (Токсовский ЦО) баскетбольная секция",
    "address": "ул. Дорожников, д. 1",
    "district": "Токсово",
    "phone": "",
    "website": "http://www.toksov.spb.ru/school.htm",
    "price": "бесплатно / символическая",
    "age": "7–16",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": 60.145873,
    "lng": 30.513992
  },
  {
    "id": "severnyi-sklon-detskaya-shkola-gornolyzhnaya-shkola-ska-filial-na-severnom-sklone",
    "slug": "severnyi-sklon-detskaya-shkola-gornolyzhnaya-shkola-ska-filial-na-severnom-sklone",
    "name": "Северный склон — детская школа Горнолыжная школа «СКА» (филиал на Северном склоне)",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Горные лыжи / сноуборд",
    "description": "Обучение горным лыжам и сноуборду, индивидуальные и групповые занятия.",
    "address": "Всеволожский р-н, ул.Офицерская, д.17Б",
    "district": "Токсово",
    "phone": "",
    "website": "https://sca-ski.ru/places/severnyj-sklon/",
    "price": "2000–6000 ₽/занятие",
    "age": "4–16",
    "format": "индивидуально / группы",
    "rating": "4.3",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1560282,
    "lng": 30.5486059
  },
  {
    "id": "kanaev-ski-club",
    "slug": "kanaev-ski-club",
    "name": "Kanaev Ski Club",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Горные лыжи",
    "description": "Горнолыжная школа с тренировками и выездами.",
    "address": "Ленинградское шоссе, 90",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/kanaevskiclub",
    "price": "5000–14000 ₽",
    "age": "5–16",
    "format": "группы",
    "rating": "5.0",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1553068,
    "lng": 30.5496235
  },
  {
    "id": "aikido",
    "slug": "aikido",
    "name": "Айкидо",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Единоборства",
    "description": "Тренировки по айкидо для детей.",
    "address": "Токсово (площадка требует подтверждения)",
    "district": "Токсово",
    "phone": "",
    "website": "https://toksovo.info/place-aykido.html",
    "price": "3000–5000 ₽",
    "age": "5–14",
    "format": "группы",
    "rating": "",
    "source": "чат + каталог кружков",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "kapoeira",
    "slug": "kapoeira",
    "name": "Капоэйра",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Единоборства / танец",
    "description": "Бразильское боевое искусство с элементами танца.",
    "address": "Гражданский проспект, Василеостровская",
    "district": "Токсово",
    "phone": "",
    "website": "http://capoeira.su/",
    "price": "2500–3300 ₽",
    "age": "5–14",
    "format": "группы",
    "rating": "",
    "source": "чат + каталог кружков",
    "status": "chat_only",
    "lat": 60.019666,
    "lng": 30.40446
  },
  {
    "id": "hudozhestvennaya-studiya-kdts",
    "slug": "hudozhestvennaya-studiya-kdts",
    "name": "Художественная студия (КДЦ)",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Рисование",
    "description": "Рисование, лепка, творческие занятия.",
    "address": "ул. Привокзальная, д.16а",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/kdctoksovo",
    "price": "2000–4000 ₽",
    "age": "4–14",
    "format": "группы",
    "rating": "",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.14926,
    "lng": 30.516588
  },
  {
    "id": "angliiskii-yazyk",
    "slug": "angliiskii-yazyk",
    "name": "Английский язык",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Языки",
    "description": "Групповые занятия английским для детей.",
    "address": "Привокзальная улица, 16А",
    "district": "Токсово",
    "phone": "",
    "website": "https://m.vk.com/wall-39719167_26458",
    "price": "3000–7000 ₽",
    "age": "4–14",
    "format": "группы",
    "rating": "",
    "source": "чат + каталог кружков",
    "status": "chat_only",
    "lat": 60.14926,
    "lng": 30.516588
  },
  {
    "id": "logopedicheskie-zanyatiya",
    "slug": "logopedicheskie-zanyatiya",
    "name": "Логопедические занятия",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Логопед",
    "description": "Индивидуальные занятия по речи и подготовка к школе.",
    "address": "Привокзальная улица, 16А",
    "district": "≈10 км",
    "phone": "",
    "website": "",
    "price": "1000–3000 ₽/занятие",
    "age": "3–10",
    "format": "индивидуально",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "severnyi-sklon",
    "slug": "severnyi-sklon",
    "name": "Северный склон",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Горные лыжи / сноуборд",
    "description": "Курорт с обучением, прокатом и трассами.",
    "address": "ул. Офицерская, 17Б",
    "district": "Токсово",
    "phone": "",
    "website": "https://severny-sklon.ru",
    "price": "2000–6000 ₽/занятие",
    "age": "16+",
    "format": "индивидуально / группы",
    "rating": "4.3",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1560282,
    "lng": 30.5486059
  },
  {
    "id": "kanaev-ski-club-2",
    "slug": "kanaev-ski-club-2",
    "name": "Kanaev Ski Club",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Горные лыжи",
    "description": "Школа горных лыж, тренировки и обучение.",
    "address": "ул. Офицерская, 17Б",
    "district": "Токсово",
    "phone": "",
    "website": "https://kanaevskiclub.ru",
    "price": "5000–15000 ₽",
    "age": "18+",
    "format": "группы",
    "rating": "5.0",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1553068,
    "lng": 30.5496235
  },
  {
    "id": "yukki-sport-club",
    "slug": "yukki-sport-club",
    "name": "Yukki Sport Club",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Горные лыжи",
    "description": "Горнолыжные занятия и тренировки.",
    "address": "Офицерская, 17Б к5",
    "district": "Токсово",
    "phone": "",
    "website": "https://www.instagram.com/yukki_skiclub/",
    "price": "по запросу",
    "age": "16+",
    "format": "группы / индивидуально",
    "rating": "",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.156429,
    "lng": 30.548145
  },
  {
    "id": "baza-ska-toksovo",
    "slug": "baza-ska-toksovo",
    "name": "База СКА Токсово",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Лыжная база",
    "description": "Спортивная база, лыжная подготовка.",
    "address": "Санаторная ул36",
    "district": "Токсово",
    "phone": "",
    "website": "https://toksovoska.orgs.biz/#:~:text=%D0%9A%D0%B0%D0%BA%D0%B8%D0%B5%20%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8%20%D0%B4%D0%BB%D1%8F%20%D0%BE%D1%82%D0%B4%D1%8B%D1%85%D0%B0%D1%8E%D1%89%D0%B8%D1%85%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%20%D0%B1%D0%B0%D0%B7%D0%B0%20%D0%A2%D0%BE%D0%BA%D1%81%D0%BE%D0%B2%D0%BE,%D0%B3%D0%B8%D0%BC%D0%BD%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D0%B7%D0%B0%D0%BB%2C%20%D0%BF%D1%80%D0%BE%D0%BA%D0%B0%D1%82%20%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%B8%D0%BD%D0%B2%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D1%8F%20%D0%B8%20%D1%81%D0%B0%D1%83%D0%BD%D1%83",
    "price": "по запросу",
    "age": "16+",
    "format": "база / тренировки",
    "rating": "4.3",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.161287,
    "lng": 30.554263
  },
  {
    "id": "gornolyzhnaya-shkola-ska",
    "slug": "gornolyzhnaya-shkola-ska",
    "name": "Горнолыжная школа СКА",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Горные лыжи",
    "description": "Тренировки по лыжам.",
    "address": "Санаторная ул., 36 (база СКА)",
    "district": "Токсово",
    "phone": "",
    "website": "http://sca-ski.ru",
    "price": "по запросу",
    "age": "16+",
    "format": "тренировки",
    "rating": "3.6",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.1602488,
    "lng": 30.5114844
  },
  {
    "id": "nikels-club",
    "slug": "nikels-club",
    "name": "Nikels Club",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Лыжный клуб",
    "description": "Лыжный клуб.",
    "address": "ул. Лесгафта, 35к1, Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://nikels.club",
    "price": "по запросу",
    "age": "16+",
    "format": "клуб / тренировки",
    "rating": "5.0",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.176421,
    "lng": 30.535129
  },
  {
    "id": "skillon",
    "slug": "skillon",
    "name": "Skillon",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Лыжный клуб",
    "description": "Спортивный клуб, лыжи.",
    "address": "ул. Лесгафта, 35, Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://skillon.ru",
    "price": "по запросу",
    "age": "16+",
    "format": "клуб / тренировки",
    "rating": "5.0",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.176421,
    "lng": 30.535129
  },
  {
    "id": "utts-kavgolovo",
    "slug": "utts-kavgolovo",
    "name": "УТЦ Кавголово",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Спорткомплекс",
    "description": "Крупный спортивный центр.",
    "address": "ул. Лесгафта, 31, Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://www.kavgolovo.center/",
    "price": "по запросу",
    "age": "16+",
    "format": "центр / тренировки",
    "rating": "4.8",
    "source": "ранее собранные открытые данные",
    "status": "verified_public",
    "lat": 60.176421,
    "lng": 30.535129
  },
  {
    "id": "tai-bo",
    "slug": "tai-bo",
    "name": "Тай Бо",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Фитнес / единоборства",
    "description": "Групповые тренировки в зале на Северном склоне.",
    "address": "Северный склон, Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "~600 ₽/занятие",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "ioga",
    "slug": "ioga",
    "name": "Йога",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Йога",
    "description": "Групповые и индивидуальные занятия йогой.",
    "address": "Токсово / Кузьмолово",
    "district": "≈10 км",
    "phone": "",
    "website": "",
    "price": "500–1500 ₽",
    "age": "18+",
    "format": "группы / индивидуально",
    "rating": "",
    "source": "локальные группы / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "pilates",
    "slug": "pilates",
    "name": "Пилатес",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Фитнес",
    "description": "Укрепление мышц, работа с осанкой.",
    "address": "Токсово / рядом",
    "district": "≈10 км",
    "phone": "",
    "website": "",
    "price": "800–2000 ₽",
    "age": "18+",
    "format": "группы",
    "rating": "",
    "source": "локальные группы / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "funktsionalnye-trenirovki",
    "slug": "funktsionalnye-trenirovki",
    "name": "Функциональные тренировки",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Фитнес",
    "description": "Групповые тренировки для силы и выносливости.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "500–1500 ₽",
    "age": "18+",
    "format": "группы",
    "rating": "",
    "source": "локальные тренировки / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "sportklub-toksovo",
    "slug": "sportklub-toksovo",
    "name": "Спортклуб Токсово",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Бег",
    "description": "Лесные маршруты, озера, самостоятельные тренировки.",
    "address": "Санаторная, 35",
    "district": "Токсово",
    "phone": "",
    "website": "https://toksovo-sport.ru/",
    "price": "бесплатно",
    "age": "16+",
    "format": "самостоятельно / клубы",
    "rating": "",
    "source": "инфраструктура местности",
    "status": "verified_public",
    "lat": 60.164811,
    "lng": 30.554604
  },
  {
    "id": "basketbol-lyubitelskii",
    "slug": "basketbol-lyubitelskii",
    "name": "Баскетбол (любительский)",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Командный спорт",
    "description": "Игры в школьных залах.",
    "address": "ул. Дорожников д. 1",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/shkola_toksovo?",
    "price": "бесплатно",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": 60.145873,
    "lng": 30.513992
  },
  {
    "id": "nastolnyi-tennis",
    "slug": "nastolnyi-tennis",
    "name": "Настольный теннис",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Игровые виды",
    "description": "Возможность играть и тренироваться.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "300–1000 ₽",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "чат жителей",
    "status": "chat_only",
    "lat": null,
    "lng": null
  },
  {
    "id": "aikido-2",
    "slug": "aikido-2",
    "name": "Айкидо",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Единоборства",
    "description": "Занятия айкидо.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "3000–5000 ₽",
    "age": "16+",
    "format": "группы",
    "rating": "",
    "source": "каталог секций / неполная верификация",
    "status": "candidate",
    "lat": null,
    "lng": null
  },
  {
    "id": "shkola-boksa",
    "slug": "shkola-boksa",
    "name": "Школа бокса",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Единоборства",
    "description": "Индивидуальные и групповые тренировки.",
    "address": "улица Лесгафта, 15",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/market-197328496?section=album_10",
    "price": "1000–3000 ₽",
    "age": "18+",
    "format": "индивидуально / группы",
    "rating": "",
    "source": "локальные предложения / неполная верификация",
    "status": "candidate",
    "lat": 60.17501,
    "lng": 30.528186
  },
  {
    "id": "parusnaya-stantsiya-kavgolovo",
    "slug": "parusnaya-stantsiya-kavgolovo",
    "name": "Парусная Станция Кавголово",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Водный спорт",
    "description": "Обучение и катание на воде.",
    "address": "Главная аллея 1",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/windsurfspb",
    "price": "1300–2000 ₽",
    "age": "16+",
    "format": "группы",
    "rating": "4.4",
    "source": "локальная инфраструктура / неполная верификация",
    "status": "candidate",
    "lat": 60.173154,
    "lng": 30.523442
  },
  {
    "id": "sup",
    "slug": "sup",
    "name": "SUP",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Водный спорт",
    "description": "Прокат и тренировки на сапах.",
    "address": "озера Токсово. Парусная Станция «Кавголово»",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/windsurfspb",
    "price": "1300–2000 ₽",
    "age": "16+",
    "format": "прокат / тренировки",
    "rating": "",
    "source": "локальная инфраструктура / неполная верификация",
    "status": "candidate",
    "lat": 60.117064,
    "lng": 30.546136
  },
  {
    "id": "kavgolovskoe-ozero",
    "slug": "kavgolovskoe-ozero",
    "name": "Кавголовское озеро",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Озеро / отдых",
    "description": "Главное озеро района — пляжи, прогулки, SUP, виндсерфинг.",
    "address": "Токсово, Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.8",
    "source": "карты / инфраструктура",
    "status": "verified_public",
    "lat": 60.1735,
    "lng": 30.528
  },
  {
    "id": "ozero-hepoyarvi",
    "slug": "ozero-hepoyarvi",
    "name": "Озеро Хепоярви",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Озеро / туризм",
    "description": "Крупное лесное озеро, популярное для прогулок, походов и рыбалки.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.9",
    "source": "карты",
    "status": "verified_public",
    "lat": 60.1714,
    "lng": 30.581707
  },
  {
    "id": "zubrovnik",
    "slug": "zubrovnik",
    "name": "Зубровник",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Экопарк",
    "description": "Питомник зубров — можно увидеть животных вблизи.",
    "address": "Токсово, ул. Совхозная",
    "district": "Токсово",
    "phone": "",
    "website": "https://zubrovnik.ru/",
    "price": "бесплатно / донаты",
    "age": "0+",
    "format": "посещение",
    "rating": "4.7",
    "source": "карты / официальные данные",
    "status": "verified_public",
    "lat": 60.1795,
    "lng": 30.543
  },
  {
    "id": "kavgolovskie-toksovskie-vysoty",
    "slug": "kavgolovskie-toksovskie-vysoty",
    "name": "Кавголовские / Токсовские высоты",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Холмы / панорамы",
    "description": "Живописные холмы, виды, лыжи зимой, прогулки летом.",
    "address": "Кавголово / Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/toksovskie-vyisotyi.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.8",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.1762,
    "lng": 30.5361
  },
  {
    "id": "stantsiya-kavgolovo-vidovaya",
    "slug": "stantsiya-kavgolovo-vidovaya",
    "name": "Станция Кавголово (видовая)",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Видовая точка",
    "description": "Красивые виды на озеро и лес с платформы.",
    "address": "Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/windsurfspb",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.6",
    "source": "карты",
    "status": "verified_public",
    "lat": 60.173,
    "lng": 30.53
  },
  {
    "id": "ekotropy-toksovo",
    "slug": "ekotropy-toksovo",
    "name": "Экотропы Токсово",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Маршруты",
    "description": "Маршруты для прогулок, бега, велосипедов.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/ecotoksovskie-vyisotyi.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "4.8",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.17,
    "lng": 30.52
  },
  {
    "id": "tserkov-arhangela-mihaila",
    "slug": "tserkov-arhangela-mihaila",
    "name": "Церковь Архангела Михаила",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Храм",
    "description": "Православный храм, историческое место.",
    "address": "ул. Лыжная, д. 16",
    "district": "Токсово",
    "phone": "",
    "website": "https://toksovo-sobor.ru/",
    "price": "бесплатно",
    "age": "0+",
    "format": "посещение",
    "rating": "4.7",
    "source": "карты",
    "status": "verified_public",
    "lat": 60.1714,
    "lng": 30.542531
  },
  {
    "id": "utts-kavgolovo-2",
    "slug": "utts-kavgolovo-2",
    "name": "УТЦ Кавголово",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Спорткомплекс",
    "description": "Крупный центр лыжных и спортивных тренировок.",
    "address": "ул.Лесгафта, д. 35",
    "district": "Токсово",
    "phone": "",
    "website": "https://www.kavgolovo.center/",
    "price": "зависит от услуг",
    "age": "0+",
    "format": "посещение / тренировки",
    "rating": "4.8",
    "source": "официальные данные",
    "status": "verified_public",
    "lat": 60.177132,
    "lng": 30.536045
  },
  {
    "id": "severnyi-sklon-2",
    "slug": "severnyi-sklon-2",
    "name": "Северный склон",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Курорт",
    "description": "Круглогодичная зона отдыха и спорта.",
    "address": "ул. Офицерская, 17Б, Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://severny-sklon.ru",
    "price": "платно",
    "age": "0+",
    "format": "посещение",
    "rating": "4.3",
    "source": "официальные данные",
    "status": "verified_public",
    "lat": 60.1560282,
    "lng": 30.5486059
  },
  {
    "id": "elovye-holmy-start",
    "slug": "elovye-holmy-start",
    "name": "Еловые холмы — старт",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Экотропа",
    "description": "Официальная стартовая точка экотропы.",
    "address": "район платформы Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/ecotoksovskie-vyisotyi.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.168,
    "lng": 30.532457
  },
  {
    "id": "malinovaya-gora-start",
    "slug": "malinovaya-gora-start",
    "name": "Малиновая гора — старт",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Экотропа",
    "description": "Официальная стартовая точка экотропы.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/ekomarshrut-malinovaya-gora.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.161705,
    "lng": 30.492562
  },
  {
    "id": "kurgolovskaya-etnotropa-start",
    "slug": "kurgolovskaya-etnotropa-start",
    "name": "Курголовская этнотропа — старт",
    "category": "Достопримечательности",
    "categoryId": "attractions",
    "subcategory": "Этнотропа",
    "description": "Официальная стартовая точка этнотропы.",
    "address": "район платформы Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "https://ooptlo.ru/kurgolovskaya-tropa.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "ООПТ",
    "status": "verified_public",
    "lat": 60.188448,
    "lng": 30.547983
  },
  {
    "id": "peschanaya-kosa-kavgolovo",
    "slug": "peschanaya-kosa-kavgolovo",
    "name": "Песчаная коса Кавголово",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Песчаный берег для закатов. Нужна полевая проверка перед публичным запуском.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "https://toksovo.info/place-peschanaya-kosa-kavgolovo.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1755,
    "lng": 30.5284
  },
  {
    "id": "tihii-zaliv-kavgolovo",
    "slug": "tihii-zaliv-kavgolovo",
    "name": "Тихий залив Кавголово",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Уединённый берег. Нужна полевая проверка.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.171,
    "lng": 30.5122
  },
  {
    "id": "zakatnaya-polyana",
    "slug": "zakatnaya-polyana",
    "name": "Закатная поляна",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Открытое поле для закатов. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/toksovolo",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1643,
    "lng": 30.5598
  },
  {
    "id": "lesnye-skaly",
    "slug": "lesnye-skaly",
    "name": "Лесные скалы",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Каменные массивы в лесу. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://eco-trails.ru/catalog/lenoblast/elovye-holmy/",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1555,
    "lng": 30.5562
  },
  {
    "id": "sosnovye-tropy-hepoyarvi",
    "slug": "sosnovye-tropy-hepoyarvi",
    "name": "Сосновые тропы Хепоярви",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Маршрут",
    "description": "Тихие лесные тропы. Нужна полевая проверка.",
    "address": "район Хепоярви",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1601,
    "lng": 30.5644
  },
  {
    "id": "dikii-bereg-hepoyarvi",
    "slug": "dikii-bereg-hepoyarvi",
    "name": "Дикий берег Хепоярви",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Тихий берег без инфраструктуры. Нужна полевая проверка.",
    "address": "район Хепоярви",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1785,
    "lng": 30.6322
  },
  {
    "id": "lesnaya-polyana-dlya-piknika",
    "slug": "lesnaya-polyana-dlya-piknika",
    "name": "Лесная поляна для пикника",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Отдых",
    "description": "Поляна для пикника. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://eco-trails.ru/catalog/lenoblast/lesnye-skazki/",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1509,
    "lng": 30.5233
  },
  {
    "id": "berezovaya-roshcha",
    "slug": "berezovaya-roshcha",
    "name": "Берёзовая роща",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Красивое место весной и осенью. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://yandex.ru/maps/org/skver_500_letiya_toksovo/121070813687/?ll=30.521232%2C60.150681&z=17",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1506,
    "lng": 30.5203
  },
  {
    "id": "peschanye-holmy-u-tropy",
    "slug": "peschanye-holmy-u-tropy",
    "name": "Песчаные холмы у тропы",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Ландшафт",
    "description": "Необычный рельеф. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://eco-trails.ru/catalog/lenoblast/elovye-holmy/",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.193975,
    "lng": 30.578718
  },
  {
    "id": "tochka-dlya-zvezdnogo-neba",
    "slug": "tochka-dlya-zvezdnogo-neba",
    "name": "Точка для звёздного неба",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Астроспот",
    "description": "Точка для наблюдения звёзд. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://www.facebook.com/sevbereg/posts/%D0%BE%D0%B7%D0%B5%D1%80%D0%BE-%D1%85%D0%B5%D0%BF%D0%BE%D1%8F%D1%80%D0%B2%D0%B8-%D0%B8-%D0%BA%D0%BB%D1%83%D0%B1-%D0%B7%D0%B0%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BE%D1%82%D0%B4%D1%8B%D1%85%D0%B0-%D1%81%D0%B5%D0%B2%D0%B5%D1%80%D0%BD%D1%8B%D0%B9-%D0%B1%D0%B5%D1%80%D0%B5%D0%B3-%D1%81-%D0%B2%D1%8B%D1%81%D0%BE%D1%82%D1%8B-%D0%BF%D1%82%D0%B8%D1%87%D1%8C%D0%B5%D0%B3%D0%BE-%D0%BF%D0%BE%D0%BB%D1%91%D1%82%D0%B0/794782244600609/",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.1714,
    "lng": 30.581707
  },
  {
    "id": "uzkii-lesnoi-spusk-k-vode",
    "slug": "uzkii-lesnoi-spusk-k-vode",
    "name": "Узкий лесной спуск к воде",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Вода",
    "description": "Небольшой спуск к воде. Нужна полевая проверка.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.165215,
    "lng": 30.501538
  },
  {
    "id": "vysokii-holm-u-kavgolovo",
    "slug": "vysokii-holm-u-kavgolovo",
    "name": "Высокий холм у Кавголово",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Видовая",
    "description": "Видовой холм. Нужна полевая проверка.",
    "address": "Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "https://eco-trails.ru/catalog/lenoblast/elovye-holmy/",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.149208,
    "lng": 30.530324
  },
  {
    "id": "staryi-sosnovyi-massiv",
    "slug": "staryi-sosnovyi-massiv",
    "name": "Старый сосновый массив",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Лес",
    "description": "Массив старых сосен. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.160124,
    "lng": 30.559281
  },
  {
    "id": "velotropa-bez-trafika",
    "slug": "velotropa-bez-trafika",
    "name": "Велотропа без трафика",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Веломаршрут",
    "description": "Тихая лесная велотропа. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://tripmir.com/routes/2087/kuzmolovo-toksovo.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.183416,
    "lng": 30.589885
  },
  {
    "id": "pole-u-kromki-lesa",
    "slug": "pole-u-kromki-lesa",
    "name": "Поле у кромки леса",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Фотоспот",
    "description": "Открытое пространство для фото. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://www.kidsreview.ru/spb/photogallery/toksovskii-zubryatnik-lenoblast-foto",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.155745,
    "lng": 30.435812
  },
  {
    "id": "lesnaya-tropa-sledov-zhivotnyh",
    "slug": "lesnaya-tropa-sledov-zhivotnyh",
    "name": "Лесная тропа следов животных",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Природа",
    "description": "Тропа со следами животных. Нужна полевая проверка.",
    "address": "Токсово",
    "district": "Токсово",
    "phone": "",
    "website": "https://yandex.com/maps/org/peshekhodny_ekologicheskiy_marshrut_yelovyye_kholmy/71623558433/?ll=30.528229%2C60.166908&z=16",
    "price": "бесплатно",
    "age": "0+",
    "format": "маршрут",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.168,
    "lng": 30.532457
  },
  {
    "id": "bezymyannyi-bereg-dlya-sup",
    "slug": "bezymyannyi-bereg-dlya-sup",
    "name": "Безымянный берег для SUP",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Вода",
    "description": "Спокойный берег. Нужна полевая проверка.",
    "address": "Кавголовское озеро",
    "district": "Токсово",
    "phone": "",
    "website": "https://toksovo.info/",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.19141,
    "lng": 30.505704
  },
  {
    "id": "malaya-smotrovaya-na-nasyp",
    "slug": "malaya-smotrovaya-na-nasyp",
    "name": "Малая смотровая на насыпь",
    "category": "Скрытые локации",
    "categoryId": "hidden",
    "subcategory": "Видовая",
    "description": "Малая видовая точка. Нужна полевая проверка.",
    "address": "Кавголово",
    "district": "Токсово",
    "phone": "",
    "website": "https://toksovo.info/place-malaya-smotrovaya-na-nasyp.html",
    "price": "бесплатно",
    "age": "0+",
    "format": "свободный доступ",
    "rating": "",
    "source": "desk research",
    "status": "candidate",
    "lat": 60.177435,
    "lng": 30.528641
  },
  {
    "id": "mikes-basketball-skills",
    "slug": "mikes-basketball-skills",
    "name": "Mike’s Basketball Skills",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Спортклуб",
    "description": "Школа баскетбола",
    "address": "ул. Лесгафта, 35, 1",
    "district": "Токсово",
    "phone": "",
    "website": "https://mikebasketballskills.ru/",
    "price": "760-8700 ₽",
    "age": "5-17",
    "format": "тренировки",
    "rating": "5.0",
    "source": "",
    "status": "",
    "lat": 60.177096,
    "lng": 30.535716
  },
  {
    "id": "skination",
    "slug": "skination",
    "name": "SkiNation",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Школа семейного спорта",
    "description": "Семейцный спорт по биатлону, конькам бегу и лыжах",
    "address": "улица Лесгафта, 35",
    "district": "Токсово",
    "phone": "",
    "website": "https://skination.ru/",
    "price": "444-9999 ₽",
    "age": "0+",
    "format": "группы",
    "rating": "5.0",
    "source": "",
    "status": "",
    "lat": 60.177426,
    "lng": 30.536122
  },
  {
    "id": "sinkai-dodze",
    "slug": "sinkai-dodze",
    "name": "Синкай Додзё",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Айкидо, Йайдо, Дзёдо",
    "description": "Обучение айкидо, йайдо и дзёдо для детей (с 7 лет) и взрослых. Развиваем силу, самообладание и гармонию тела и духа через традиции японских боевых искусств.",
    "address": "Привокзальная улица, 10, лит. А",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/sinkaytoksovo",
    "price": "от 500 ₽",
    "age": "7+",
    "format": "группы",
    "rating": "4.0",
    "source": "",
    "status": "",
    "lat": 60.1074,
    "lng": 30.5622
  },
  {
    "id": "gornolyzhnaya-shkola-natali-zaharovoi",
    "slug": "gornolyzhnaya-shkola-natali-zaharovoi",
    "name": "Горнолыжная школа Натальи Захаровой",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Горнолыжная школа",
    "description": "Специализированная спортивная школа",
    "address": "Офицерская улица, 17Б",
    "district": "Токсово",
    "phone": "",
    "website": "https://nzakharova.ru",
    "price": "от 6000 ₽",
    "age": "от 3",
    "format": "тренировки",
    "rating": "4.3",
    "source": "",
    "status": "",
    "lat": 60.1074,
    "lng": 30.5622
  },
  {
    "id": "snegir-shkola-figurnogo-kataniya",
    "slug": "snegir-shkola-figurnogo-kataniya",
    "name": "\"Снегирь\", школа фигурного катания",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Спортивная школа фигурного катания",
    "description": "Тренировки включают разминку, ОФП и занятие на льду с элементами хореографии. Проводится обучение на катке Ice Kavgolovo.",
    "address": "Лесгафта, 15А",
    "district": "Токсово",
    "phone": "",
    "website": "https://spb.kartasporta.ru/catalogue/sport/studiya_figurnogo_kataniya_snegir_329/",
    "price": "1200-6700 ₽",
    "age": "3+",
    "format": "группы",
    "rating": "",
    "source": "",
    "status": "",
    "lat": 60.1495,
    "lng": 30.5544
  },
  {
    "id": "detskii-tsentr-plastilinovaya-vorona",
    "slug": "detskii-tsentr-plastilinovaya-vorona",
    "name": "Детский центр \"Пластилиновая ворона\"",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "при МКУ \"Культурно-досуговый центр\"",
    "description": "Для детей, включает творческие, спортивные и развивающие занятия",
    "address": "Привокзальная улица, 16А",
    "district": "Токсово",
    "phone": "",
    "website": "https://detskiy-centr-toksovo.orgs.biz/",
    "price": "140-750 ₽",
    "age": "2026-07-03 00:00:00",
    "format": "группы",
    "rating": "4.3",
    "source": "",
    "status": "",
    "lat": 60.149725,
    "lng": 30.511027
  },
  {
    "id": "detskaya-basketbolnaya-akademiya-nasledie",
    "slug": "detskaya-basketbolnaya-akademiya-nasledie",
    "name": "Детская баскетбольная академия \"Наследие\"",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Баскетбол",
    "description": "Детская баскетбольная академия",
    "address": "Санаторная улица, 35",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/nasledie_basketball",
    "price": "3000-7000 ₽",
    "age": "2026-08-04 00:00:00",
    "format": "группы",
    "rating": "4.0",
    "source": "",
    "status": "",
    "lat": 60.149725,
    "lng": 30.511027
  },
  {
    "id": "dinamo",
    "slug": "dinamo",
    "name": "Динамо",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "лыжная база",
    "description": "Активный отдых, включая катание на лыжах, ватрушках и санках",
    "address": "Тупиковый переулок, 5",
    "district": "Токсово",
    "phone": "",
    "website": "https://2gis.ru/spb/gallery/firm/5348553838544557/photoId/30258560069057996",
    "price": "бесплатно",
    "age": "5+",
    "format": "группы",
    "rating": "3.8",
    "source": "",
    "status": "",
    "lat": 60.149725,
    "lng": 30.511027
  },
  {
    "id": "rannee-plavanie-birthlight-s-kolobochki-klub",
    "slug": "rannee-plavanie-birthlight-s-kolobochki-klub",
    "name": "Раннее плавание Birthlight с Колобочки клуб",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Бассейн",
    "description": "Детский бассейн",
    "address": "Санаторная ул., 33а",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/plavaemtoksovo",
    "price": "6000-17000 ₽",
    "age": "0-7",
    "format": "индивидуально / группы",
    "rating": "4.6",
    "source": "",
    "status": "",
    "lat": 60.16334,
    "lng": 30.553922
  },
  {
    "id": "tsentr-hudozhestvennoi-gimnastiki-mir",
    "slug": "tsentr-hudozhestvennoi-gimnastiki-mir",
    "name": "Центр Художественной Гимнастики \"МИР\"",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Художественная гимнастика",
    "description": "Спортивная база УТЦ «КАВГОЛОВО",
    "address": "улица Лесгафта, 35",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/mir_rg",
    "price": "6500-13000 ₽",
    "age": "3-16",
    "format": "группы",
    "rating": "4.0",
    "source": "",
    "status": "",
    "lat": 60.1501,
    "lng": 30.5542
  },
  {
    "id": "hudozhestvennaya-gimnastika-i-rastyazhka-sk-vozduh",
    "slug": "hudozhestvennaya-gimnastika-i-rastyazhka-sk-vozduh",
    "name": "Художественная гимнастика и растяжка СК «Воздух»",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Художественная гимнастика",
    "description": "Художественная гимнастика и растяжка",
    "address": "Санаторная улица 36",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/club232006800",
    "price": "500-5000 ₽",
    "age": "3+",
    "format": "группы",
    "rating": "5.0",
    "source": "",
    "status": "",
    "lat": 60.149725,
    "lng": 30.511027
  },
  {
    "id": "kidsurf",
    "slug": "kidsurf",
    "name": "KIDSURF",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Виндсёрфинг",
    "description": "Школа виндсёрфинга",
    "address": "Озёрная улица, 1",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/kidsurf_sailingclub",
    "price": "1500-9000 ₽",
    "age": "7+",
    "format": "индивидуально / группы",
    "rating": "4.8",
    "source": "",
    "status": "",
    "lat": 60.1501,
    "lng": 30.5542
  },
  {
    "id": "i-love-supersport",
    "slug": "i-love-supersport",
    "name": "I love supersport",
    "category": "Лыжная школа",
    "categoryId": "sport",
    "subcategory": "Лыжный клуб",
    "description": "Крупнейшая в мире школа циклических видов спорта для взрослых.",
    "address": "улица Лесгафта, 35",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/iloveskiingspb",
    "price": "2000-6000 ₽",
    "age": "7+",
    "format": "индивидуально / группы",
    "rating": "4.5",
    "source": "",
    "status": "",
    "lat": 60.178,
    "lng": 30.5483
  },
  {
    "id": "shkola-sovremennyh-tantsev",
    "slug": "shkola-sovremennyh-tantsev",
    "name": "Школа современных танцев",
    "category": "Танцы",
    "categoryId": "children",
    "subcategory": "Современные танцы",
    "description": "Центр творчества и интеллектуального развития",
    "address": "Привокзальная площадь, 1",
    "district": "Токсово",
    "phone": "",
    "website": "",
    "price": "600-500 ₽",
    "age": "7-14",
    "format": "группы",
    "rating": "5.0",
    "source": "",
    "status": "",
    "lat": 60.1495,
    "lng": 30.5125
  },
  {
    "id": "toksovo-wakesport-wake-park",
    "slug": "toksovo-wakesport-wake-park",
    "name": "Toksovo Wakesport Wake Park",
    "category": "Спорт для взрослых",
    "categoryId": "sport",
    "subcategory": "Самый первый вейк-парк в России",
    "description": "Вейк-парк",
    "address": "залив Аунеланлахти",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/wakesportoksovo",
    "price": "1200-4500 ₽",
    "age": "16+",
    "format": "индивидуально / группы",
    "rating": "4.3",
    "source": "",
    "status": "",
    "lat": 60.1564,
    "lng": 30.548
  },
  {
    "id": "belyi-medved",
    "slug": "belyi-medved",
    "name": "Белый медведь",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Смешанные единоборства",
    "description": "дзюдо, смешанные единоборства, спортивная борьба, бокс, кикбоксинг",
    "address": "Привокзальная ул., 16А,",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/judotoksovo",
    "price": "800-7500 ₽",
    "age": "4-16",
    "format": "Индивидуально / группы",
    "rating": "4.0",
    "source": "",
    "status": "",
    "lat": 60.149597,
    "lng": 30.512255
  },
  {
    "id": "wake-u-p-wake",
    "slug": "wake-u-p-wake",
    "name": "Wake U.P. wake",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Вейк-клуб",
    "description": "катание за катером и реверсивной лебёдкой с парком.",
    "address": "улица Лесгафта, 28А.",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/wakeupwakestation",
    "price": "500 ₽",
    "age": "5+",
    "format": "Индивидуально / группы",
    "rating": "4.2",
    "source": "",
    "status": "",
    "lat": 60.1751,
    "lng": 30.5303
  },
  {
    "id": "shahmatnyi-klub-kuzmolovo",
    "slug": "shahmatnyi-klub-kuzmolovo",
    "name": "Шахматный клуб Кузьмолово",
    "category": "Дети",
    "categoryId": "children",
    "subcategory": "Шахматный клуб",
    "description": "Турниры и обучение по шахматам",
    "address": "Привокзальная ул., 10",
    "district": "Токсово",
    "phone": "",
    "website": "https://kuzmolovo-chessclub.ru/o-nas-stati-i-materialy/svyazatsya-s-nami.html",
    "price": "2500-5000 ₽",
    "age": "6+",
    "format": "Индивидуально / группы",
    "rating": "4.0",
    "source": "",
    "status": "",
    "lat": 60.1498,
    "lng": 30.511
  },
  {
    "id": "kolobochki-klub",
    "slug": "kolobochki-klub",
    "name": "Колобочки клуб",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Бассейн, спортивный клуб",
    "description": "Раннее плавание для грудничков и малышей до 4 лет, аквааэробика для беременных, семейная баня с бассейном и проведение детских праздников",
    "address": "Санаторная ул., 33А",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/kolobochki",
    "price": "950-10000 ₽",
    "age": "3+",
    "format": "Индивидуально / группы",
    "rating": "4.0",
    "source": "",
    "status": "",
    "lat": 60.1584,
    "lng": 30.5407
  },
  {
    "id": "sportivnaya-baza-vifk",
    "slug": "sportivnaya-baza-vifk",
    "name": "Спортивная база ВИФК",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Спортивная школа",
    "description": "Лыжная трасса Военного Института Физической Культуры",
    "address": "Ул. Советов район Тупикового переулка и озера Чайное.",
    "district": "Токсово",
    "phone": "",
    "website": "https://vk.com/wall-101240487_1731",
    "price": "500 ₽",
    "age": "7+",
    "format": "Индивидуально / группы",
    "rating": "4.4",
    "source": "",
    "status": "",
    "lat": 60.1801,
    "lng": 30.5592
  },
  {
    "id": "golden-horses",
    "slug": "golden-horses",
    "name": "Голден Хорсес",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Конюшня",
    "description": "Конный спорт, конные прогулки, профессиональные фотосессии",
    "address": "Всеволожский район, Токсовское городское поселение, парк Изумрудное озеро",
    "district": "Токсово",
    "phone": "",
    "website": "https://мы-миниферма.рф",
    "price": "590-5000 ₽",
    "age": "3+",
    "format": "индивидуально",
    "rating": "5.0",
    "source": "",
    "status": "",
    "lat": 60.15307,
    "lng": 30.473597
  },
  {
    "id": "toksovskaya-banya",
    "slug": "toksovskaya-banya",
    "name": "Токсовская баня",
    "category": "Взрослые",
    "categoryId": "sport",
    "subcategory": "Общественная баня",
    "description": "Традиционная муниципальная общественная баня с раздельными мужскими и женскими днями.",
    "address": "Привокзальная ул., д. 10. Или д. 1.",
    "district": "Токсово",
    "phone": "",
    "website": "https://mp-toksovskaja-banja.clients.site/",
    "price": "230 ₽",
    "age": "18+",
    "format": "Группы",
    "rating": "4.8",
    "source": "",
    "status": "",
    "lat": 60.1504,
    "lng": 30.5098
  },
  {
    "id": "domik-ohotnika",
    "slug": "domik-ohotnika",
    "name": "Домик Охотника",
    "category": "Дети и взрослые",
    "categoryId": "children",
    "subcategory": "Гостевой дом",
    "description": "ютный гостевой дом в хвойном лесу. Предлагает номера для проживания, аренду саун с бассейнами, кафе и площадки для проведения праздников.",
    "address": "Санаторная ул., 33А",
    "district": "Токсово",
    "phone": "",
    "website": "https://k-vizit.com/oteli/domik-oxotnika",
    "price": "2150 ₽",
    "age": "5+",
    "format": "Индивидуально / группы",
    "rating": "4.7",
    "source": "",
    "status": "",
    "lat": 60.1583,
    "lng": 30.5407
  },
  {
    "id": "sportivnaya-baza-im-lesgafta",
    "slug": "sportivnaya-baza-im-lesgafta",
    "name": "Спортивная База им. Лесгафта",
    "category": "Студенты",
    "categoryId": "sport",
    "subcategory": "Учебно-тренировочный центр",
    "description": "Учебно-тренировочный центр профильного университета.",
    "address": "ул. Лесгафта, 3",
    "district": "Токсово",
    "phone": "",
    "website": "https://lesgaft.spb.ru/ru",
    "price": "1800-5500 ₽",
    "age": "17-18",
    "format": "Индивидуально / группы",
    "rating": "5.0",
    "source": "",
    "status": "",
    "lat": 60.177132,
    "lng": 30.536045
  }
];
