server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Отдаём статику
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статических файлов
    location ~* \.(css|js|svg|png|jpg|ico|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    gzip on;
    gzip_types text/plain text/css application/javascript image/svg+xml;
}
